const products = [
  {
    id: 1,
    category: "A",
    name: "Dao",
    title: "products.product1.title",
    description: "products.product1.description",
    tagline: "products.product1.tagline",
    overview: "products.product1.overview",
    features: [
      { feature: "products.product1.features.feature1", benefit: "products.product1.benefits.benefit1" },
      { feature: "products.product1.features.feature2", benefit: "products.product1.benefits.benefit2" },
      { feature: "products.product1.features.feature3", benefit: "products.product1.benefits.benefit3" },
      { feature: "products.product1.features.feature4", benefit: "products.product1.benefits.benefit4" },
      { feature: "products.product1.features.feature5", benefit: "products.product1.benefits.benefit5" },
    ],
    useCases: [
      { useCase: "products.product1.usecases.usecase1" },
      { useCase: "products.product1.usecases.usecase2" },
      { useCase: "products.product1.usecases.usecase3" },
    ],
    faq: [
      { question: "products.product1.faq.questions.questoin1", answer: "products.product1.faq.answers.answer1" },
    ],
    img: "https://via.placeholder.com/150"
  },
  {
    id: 2,
    category: "A",
    name: "Construction Modulaire",
    title: "products.product1.title",
    description: "products.product1.description",
    tagline: "products.product1.tagline",
    overview: "products.product1.overview",
    features: [
      { feature: "products.product2.features.feature1", benefit: "products.product2.benefits.benefit1" },
      { feature: "products.product2.features.feature2", benefit: "products.product2.benefits.benefit2" },
      { feature: "products.product2.features.feature3", benefit: "products.product2.benefits.benefit3" },
      { feature: "products.product2.features.feature4", benefit: "products.product2.benefits.benefit4" },
      { feature: "products.product2.features.feature5", benefit: "products.product2.benefits.benefit5" },
    ],
    useCases: [
      { useCase: "products.product2.usecases.usecase1" },
      { useCase: "products.product2.usecases.usecase2" },
      { useCase: "products.product2.usecases.usecase3" },
      { useCase: "products.product2.usecases.usecase4" },
    ],
    faq: [
      { question: "products.product2.faq.questions.questoin1", answer: "products.product2.faq.answers.answer1" },
      { question: "products.product2.faq.questions.questoin2", answer: "products.product2.faq.answers.answer2" },
    ],
    img: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    category: "A",
    name: "Structure Metallique",
    title: "products.product3.title",
    description: "products.product3.description",
    tagline: "products.product3.tagline",
    overview: "products.product3.overview",
    features: [
      { feature: "products.product3.features.feature1", benefit: "products.product2.benefits.benefit1" },
      { feature: "products.product3.features.feature2", benefit: "products.product2.benefits.benefit2" },
    ],
    useCases: [
      { useCase: "products.product3.usecases.usecase1" },
      { useCase: "products.product3.usecases.usecase2" },
      { useCase: "products.product3.usecases.usecase3" },
      { useCase: "products.product3.usecases.usecase4" },
    ],
    faq: [
      { question: "products.product3.faq.questions.questoin1", answer: "products.product3.faq.answers.answer1" },
    ],
    img: "https://via.placeholder.com/150",
  },
  {
    id: 4,
    category: "B",
    name: "Maintenance",
    title: "products.product4.title",
    description: "products.product4.description",
    tagline: "products.product4.tagline",
    overview: "products.product4.overview",
    features: [
      { feature: "products.product4.features.feature1", benefit: "products.product4.benefits.benefit1" },
      { feature: "products.product4.features.feature2", benefit: "products.product4.benefits.benefit2" },
      { feature: "products.product4.features.feature3", benefit: "products.product4.benefits.benefit3" },
      { feature: "products.product4.features.feature4", benefit: "products.product4.benefits.benefit4" },
    ],
    useCases: [
      { useCase: "products.product3.usecases.usecase1" },
      { useCase: "products.product3.usecases.usecase2" },
      { useCase: "products.product3.usecases.usecase3" },
      { useCase: "products.product3.usecases.usecase4" },
    ],
    faq: [
      { question: "products.product4.faq.questions.questoin1", answer: "products.product4.faq.answers.answer1" },
      { question: "products.product4.faq.questions.questoin2", answer: "products.product4.faq.answers.answer2" },
    ],
    img: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    category: "A",
    name: "Menuiserie metallique",
    title: "products.product5.title",
    description: "products.product5.description",
    tagline: "products.product5.tagline"
    ,
    overview: "products.product5.overview",
    features: [
      { feature: "products.product5.features.feature1", benefit: "products.product5.benefits.benefit1" },
      { feature: "products.product5.features.feature2", benefit: "products.product5.benefits.benefit2" },
      { feature: "products.product5.features.feature3", benefit: "products.product5.benefits.benefit3" },
      { feature: "products.product5.features.feature4", benefit: "products.product5.benefits.benefit4" },
      { feature: "products.product5.features.feature5", benefit: "products.product5.benefits.benefit5" },
    ],
    useCases: [
      { useCase: "products.product5.usecases.usecase1" },
      { useCase: "products.product5.usecases.usecase2" },
      { useCase: "products.product5.usecases.usecase3" },
      { useCase: "products.product5.usecases.usecase4" },
    ],
    faq: [
      { question: "products.product5.faq.questions.questoin1", answer: "products.product5.faq.answers.answer1" },
      { question: "products.product5.faq.questions.questoin2", answer: "products.product5.faq.answers.answer2" },
    ],
    img: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    category: "B",
    name: "Construction fabrication serie",
    title: "products.product6.title",
    description: "products.product6.description",
    tagline: "products.product6.tagline",
    overview: "products.product6.overview",
    features: [
      { feature: "products.product6.features.feature1", benefit: "products.product6.benefits.benefit1" },
      { feature: "products.product6.features.feature2", benefit: "products.product6.benefits.benefit2" },
      { feature: "products.product6.features.feature3", benefit: "products.product6.benefits.benefit3" },
    ],
    useCases: [
      { useCase: "products.product6.usecases.usecase1" },
      { useCase: "products.product6.usecases.usecase2" },
    ],
    faq: [
      { question: "products.product6.faq.questions.questoin1", answer: "products.product6.faq.answers.answer1" },
    ],
    img: "https://via.placeholder.com/150",
  },
  {
    id: 7,
    category: "C",
    name: "Decoupage Netoiyage",
    title: "products.product7.title",
    description: "products.product7.description",
    tagline: "products.product7.tagline",
    overview: "products.product7.overview",
    features: [
      { feature: "products.product7.features.feature1", benefit: "products.product7.benefits.benefit1" },
      { feature: "products.product7.features.feature2", benefit: "products.product7.benefits.benefit2" },
    ],
    useCases: [
      { useCase: "products.product7.usecases.usecase1" },
      { useCase: "products.product7.usecases.usecase2" },
      { useCase: "products.product7.usecases.usecase3" },
      { useCase: "products.product7.usecases.usecase4" },
    ],
    faq: [
      { question: "products.product7.faq.questions.questoin1", answer: "products.product7.faq.answers.answer1" },
    ],
    img: "https://via.placeholder.com/150",
  },
  {
    id: 8,
    category: "C",
    name: "Traitement chimique",
    title: "products.product8.title",
    description: "products.product8.description",
    tagline: "products.product8.tagline",
    overview: "products.product8.overview",
    features: [
      { feature: "products.product8.features.feature1", benefit: "products.product8.benefits.benefit1" },
      { feature: "products.product8.features.feature2", benefit: "products.product8.benefits.benefit2" },
    ],
    useCases: [
      { useCase: "products.product8.usecases.usecase1" },
    ],
    faq: [
      { question: "products.product8.faq.questions.questoin1", answer: "products.product8.faq.answers.answer1" },
    ],
    img: "https://via.placeholder.com/150",
  },
  {
    id: 9,
    category: "C",
    name: "Traitement de peinture",
    title: "products.product9.title",
    description: "products.product9.description",
    tagline: "products.product9.tagline",
    overview: "products.product9.overview",
    features: [
      { feature: "products.product9.features.feature1", benefit: "products.product9.benefits.benefit1" },
      { feature: "products.product9.features.feature2", benefit: "products.product9.benefits.benefit2" },
      { feature: "products.product9.features.feature3", benefit: "products.product9.benefits.benefit3" },
      { feature: "products.product9.features.feature4", benefit: "products.product9.benefits.benefit4" },
      { feature: "products.product9.features.feature5", benefit: "products.product9.benefits.benefit5" },
    ],
    useCases: [
      { useCase: "products.product9.usecases.usecase1" },
      { useCase: "products.product9.usecases.usecase2" },
      { useCase: "products.product9.usecases.usecase3" },
    ],
    faq: [
      { question: "products.product9.faq.questions.questoin1", answer: "products.product9.faq.answers.answer1" },
    ],
    img: "https://via.placeholder.com/150",
    // },
  }
];

export default products;